from __future__ import annotations

import math
from typing import Any, Dict, List, Optional, Sequence, Tuple

try:
    import numpy as np
except ImportError:  # pragma: no cover – numpy is optional for stub tests
    np = None  # type: ignore[assignment]


def _sigmoid(x: float) -> float:
    """Numerically stable sigmoid."""
    if x >= 0:
        return 1.0 / (1.0 + math.exp(-x))
    exp_x = math.exp(x)
    return exp_x / (1.0 + exp_x)


class ValueModel:
    """Learned value model that scores (partial) rollouts.

    The value model is trained with binary cross-entropy loss on
    (rollout, binary_reward) pairs.  At inference time it produces a
    scalar score in [0, 1] representing the predicted probability that
    the rollout will eventually succeed (receive reward 1).

    Only *policy tokens* (tokens generated by the model, not environment
    / tool-call tokens) are used for scoring, following the masking
    strategy described in the KARL paper (Section 5).
    """

    def __init__(
        self,
        weights: Optional[Any] = None,
        bias: float = 0.0,
        feature_dim: int = 64,
    ):
        """
        Args:
            weights: Weight vector (numpy array or list of floats).
                If *None*, initialised to zeros of length *feature_dim*.
            bias: Scalar bias term.
            feature_dim: Dimensionality when weights are auto-initialised.
        """
        self.feature_dim = feature_dim
        self.bias = bias
        if weights is not None:
            if np is not None:
                self.weights = np.array(weights, dtype=float)
            else:
                self.weights = list(weights)
        else:
            if np is not None:
                self.weights = np.zeros(feature_dim, dtype=float)
            else:
                self.weights = [0.0] * feature_dim

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------

    def fit(
        self,
        rollouts: Sequence[Any],
        rewards: Sequence[float],
        *,
        lr: float = 0.01,
        epochs: int = 10,
        mask_policy: bool = True,
    ) -> Dict[str, Any]:
        """Train the value model using binary cross-entropy loss.

        Each rollout is converted to a fixed-size feature vector (via
        :meth:`_featurise`) and the model is optimised with SGD.

        Args:
            rollouts: Sequence of rollout objects (dicts or token lists).
            rewards: Binary reward labels (0 or 1) for each rollout.
            lr: Learning rate for SGD.
            epochs: Number of training passes.
            mask_policy: If *True*, apply policy-token masking before
                featurisation.

        Returns:
            A dict with training statistics (``final_loss``, ``epochs``).
        """
        if np is None:
            raise RuntimeError("numpy is required for ValueModel.fit()")

        features = []
        for rollout in rollouts:
            if mask_policy:
                masked = self.mask_policy_tokens(rollout)
            else:
                masked = rollout
            features.append(self._featurise(masked))

        X = np.array(features, dtype=float)  # (N, D)
        y = np.array(rewards, dtype=float)  # (N,)

        # Ensure weight vector dimension matches features.
        D = X.shape[1]
        if len(self.weights) != D:
            self.weights = np.zeros(D, dtype=float)
            self.feature_dim = D

        w = np.array(self.weights, dtype=float)
        b = float(self.bias)
        n = len(y)

        loss_history: List[float] = []
        for epoch in range(epochs):
            logits = X @ w + b  # (N,)
            preds = 1.0 / (1.0 + np.exp(-np.clip(logits, -500, 500)))  # sigmoid

            # Binary cross-entropy loss.
            eps = 1e-12
            loss = -np.mean(
                y * np.log(preds + eps) + (1 - y) * np.log(1 - preds + eps)
            )
            loss_history.append(float(loss))

            # Gradient of BCE w.r.t. logits: (pred - y)
            grad = preds - y  # (N,)
            dw = (X.T @ grad) / n
            db = np.mean(grad)

            w -= lr * dw
            b -= lr * db

        self.weights = w
        self.bias = float(b)

        return {
            "final_loss": loss_history[-1] if loss_history else float("nan"),
            "epochs": epochs,
            "loss_history": loss_history,
        }

    # ------------------------------------------------------------------
    # Scoring
    # ------------------------------------------------------------------

    def score_partial_rollout(self, rollout: Any) -> float:
        """Score a partial rollout (in-progress trajectory).

        The rollout is masked, featurised, and passed through the linear
        model + sigmoid to produce a probability in [0, 1].
        """
        masked = self.mask_policy_tokens(rollout)
        feats = self._featurise(masked)
        return self._predict_single(feats)

    def score_rollout(self, rollout: Any) -> float:
        """Score a complete rollout.

        Same as :meth:`score_partial_rollout` but semantically indicates
        the rollout is finished.
        """
        masked = self.mask_policy_tokens(rollout)
        feats = self._featurise(masked)
        return self._predict_single(feats)

    # ------------------------------------------------------------------
    # Masking
    # ------------------------------------------------------------------

    def mask_policy_tokens(self, rollout: Any) -> Any:
        """Mask out non-policy tokens from a rollout.

        Policy tokens are those generated by the model itself.  Environment
        tokens (tool outputs, retrieval results, etc.) are replaced with a
        sentinel so they do not influence the value estimate.

        The implementation handles several rollout representations:

        - **dict with 'steps'**: each step that has ``role == "tool"`` or
          ``role == "environment"`` has its content replaced.
        - **list of dicts**: same logic applied element-wise.
        - **list of token-ids / strings**: returned as-is (assumed to
          already be policy-only).
        """
        if isinstance(rollout, dict):
            import copy as _copy
            masked = _copy.deepcopy(rollout)
            steps = masked.get("steps", [])
            for step in steps:
                if isinstance(step, dict):
                    role = step.get("role", "")
                    if role in ("tool", "environment", "system"):
                        step["content"] = "[MASKED]"
                        step["masked"] = True
            return masked

        if isinstance(rollout, (list, tuple)):
            masked_items = []
            for item in rollout:
                if isinstance(item, dict):
                    role = item.get("role", "")
                    if role in ("tool", "environment", "system"):
                        item = dict(item, content="[MASKED]", masked=True)
                masked_items.append(item)
            return masked_items

        # Scalar / opaque object -- return as-is.
        return rollout

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _featurise(self, rollout: Any) -> List[float]:
        """Convert a (potentially masked) rollout into a fixed-length feature vector.

        This is a lightweight feature extraction that works without a neural
        encoder.  It computes simple statistics over the rollout:

        - Number of steps / tokens
        - Average content length of policy steps
        - Fraction of steps that are policy (not masked)
        - Various positional features

        The vector is zero-padded or truncated to ``self.feature_dim``.
        """
        feats: List[float] = []

        if isinstance(rollout, dict):
            steps = rollout.get("steps", [])
        elif isinstance(rollout, (list, tuple)):
            steps = list(rollout)
        else:
            return [0.0] * self.feature_dim

        num_steps = len(steps)
        feats.append(float(num_steps))

        # Count policy vs masked steps.
        policy_count = 0
        total_content_len = 0
        for step in steps:
            if isinstance(step, dict):
                if not step.get("masked", False):
                    policy_count += 1
                    content = step.get("content", "")
                    total_content_len += len(str(content))
            else:
                policy_count += 1
                total_content_len += len(str(step))

        feats.append(float(policy_count))
        feats.append(float(total_content_len))
        feats.append(
            float(policy_count) / max(num_steps, 1)
        )  # policy fraction
        feats.append(
            float(total_content_len) / max(policy_count, 1)
        )  # avg content len

        # Pad or truncate.
        if len(feats) < self.feature_dim:
            feats.extend([0.0] * (self.feature_dim - len(feats)))
        else:
            feats = feats[: self.feature_dim]

        return feats

    def _predict_single(self, features: Sequence[float]) -> float:
        """Linear model + sigmoid for a single feature vector."""
        if np is not None:
            w = np.array(self.weights, dtype=float)
            x = np.array(features, dtype=float)
            # Handle dimension mismatch gracefully.
            min_dim = min(len(w), len(x))
            logit = float(np.dot(w[:min_dim], x[:min_dim])) + self.bias
        else:
            min_dim = min(len(self.weights), len(features))
            logit = (
                sum(
                    self.weights[i] * features[i] for i in range(min_dim)
                )
                + self.bias
            )
        return _sigmoid(logit)


class ValueModelTrainer:
    """High-level trainer for the binary-reward value model.

    Wraps :class:`ValueModel` with additional training utilities such as
    data preparation, train/validation splitting, and logging.

    Attributes:
        binary_reward_only: When *True* (the default, matching the paper),
            only binary (0/1) reward labels are used.  Continuous rewards
            are thresholded at 0.5.
    """

    binary_reward_only = True

    def __init__(
        self,
        value_model: Optional[ValueModel] = None,
        *,
        binary_reward_only: bool = True,
        lr: float = 0.01,
        epochs: int = 20,
    ):
        self.value_model = value_model or ValueModel()
        self.binary_reward_only = binary_reward_only
        self.lr = lr
        self.epochs = epochs

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------

    def fit(
        self,
        rollouts: Sequence[Any],
        rewards: Sequence[float],
        *,
        lr: Optional[float] = None,
        epochs: Optional[int] = None,
        validation_split: float = 0.0,
    ) -> Dict[str, Any]:
        """Train the value model on (rollout, reward) pairs.

        If ``binary_reward_only`` is set, rewards are binarised: values
        >= 0.5 become 1.0, everything else becomes 0.0.

        Args:
            rollouts: Sequence of rollout objects.
            rewards: Reward labels.
            lr: Override learning rate.
            epochs: Override number of epochs.
            validation_split: Fraction of data to hold out for validation.

        Returns:
            A dict with training statistics.
        """
        lr = lr or self.lr
        epochs = epochs or self.epochs

        # Binarise rewards if required.
        processed_rewards: List[float] = []
        for r in rewards:
            if self.binary_reward_only:
                processed_rewards.append(1.0 if r >= 0.5 else 0.0)
            else:
                processed_rewards.append(float(r))

        # Optional validation split.
        n = len(rollouts)
        val_n = int(n * validation_split)
        if val_n > 0 and val_n < n:
            train_rollouts = list(rollouts[:-val_n])
            train_rewards = processed_rewards[:-val_n]
            val_rollouts = list(rollouts[-val_n:])
            val_rewards = processed_rewards[-val_n:]
        else:
            train_rollouts = list(rollouts)
            train_rewards = processed_rewards
            val_rollouts = []
            val_rewards = []

        result = self.value_model.fit(
            train_rollouts,
            train_rewards,
            lr=lr,
            epochs=epochs,
            mask_policy=True,
        )

        # Compute validation loss if applicable.
        if val_rollouts:
            val_scores = [
                self.value_model.score_rollout(r) for r in val_rollouts
            ]
            eps = 1e-12
            val_loss = -sum(
                y * math.log(p + eps) + (1 - y) * math.log(1 - p + eps)
                for y, p in zip(val_rewards, val_scores)
            ) / len(val_rewards)
            result["val_loss"] = val_loss

        result["num_train"] = len(train_rollouts)
        result["num_val"] = len(val_rollouts)
        return result

    # ------------------------------------------------------------------
    # Delegated methods
    # ------------------------------------------------------------------

    def mask_policy_tokens(self, rollout: Any) -> Any:
        """Delegate to the underlying :class:`ValueModel`."""
        return self.value_model.mask_policy_tokens(rollout)

    def score_partial_rollout(self, rollout: Any) -> float:
        """Delegate to the underlying :class:`ValueModel`."""
        return self.value_model.score_partial_rollout(rollout)

    def score_rollout(self, rollout: Any) -> float:
        """Delegate to the underlying :class:`ValueModel`."""
        return self.value_model.score_rollout(rollout)
